# Nome da aplicação
quarkus.application.name=kidsgrace-audit-service


# ========================================
# Configuração do canal de entrada "users"
# ========================================

# Canal user-audit
mp.messaging.incoming.user-audit.connector=smallrye-kafka

# Tópico Kafka
mp.messaging.incoming.user-audit.topic=users.events

# Broker Kafka
mp.messaging.incoming.user-audit.bootstrap.servers=localhost:9092

# Consumer Group
mp.messaging.incoming.user-audit.group.id=kidsgrace-audit-service


# ========================================
# Configuração do canal de entrada "toys"
# ========================================

# Canal toy-audit
mp.messaging.incoming.toy-audit.connector=smallrye-kafka

# Tópico Kafka
mp.messaging.incoming.toy-audit.topic=toys.events

# Broker Kafka
mp.messaging.incoming.toy-audit.bootstrap.servers=localhost:9092

# Consumer Group
mp.messaging.incoming.toy-audit.group.id=kidsgrace-audit-service


# ========================================
# Banco de dados
# ========================================

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=root
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/kidsgrace

# Hibernate ORM
quarkus.hibernate-orm.schema-management.strategy=update


# Porta da aplicação
quarkus.http.port=8090