# Nome da aplicação
quarkus.application.name=kidsgrace-audit-service

# Configuração do canal de entrada "logs"
# Canal audit
mp.messaging.incoming.audit.connector=smallrye-kafka

# Tópico Kafka
mp.messaging.incoming.audit.topic=logs

# Broker Kafka
mp.messaging.incoming.audit.bootstrap.servers=localhost:9092

# Consumer Group
mp.messaging.incoming.audit.group.id=kidsgrace-audit-service

quarkus.http.port=8090
